#!/usr/bin/env bash
#
# Release manually
#

set -eEuo pipefail
cd "$(dirname "$0")/.."

cargo run -- examples/lyrx/home.md build/
# FIXME temporary hack to support 404 pages, change when you can keep the name
mv build/404/index.html build/404.html
rm -r build/404
cd build/
git init
git remote add origin https://github.com/lyr-7D1h/lyrx
git add .
git commit -m "manual release"
git push -f