use log::warn;
use proc_virtual_dom::dom;
use serde::Deserialize;
use serde_extensions::Overwrite;

use crate::{
    renderer::{RenderContext, TokenRenderer, modules::RendererModule},
    sitetree::{Relation, SiteNode, Stylesheet},
};
use virtual_dom::{Document, DomNode, DomNodeKind, to_attributes};

pub const LAYOUT_STYLESHEET: &[u8] = include_bytes!("./layout_module/layout.css");

/// Footer options, read from page attributes under `[layout.footer]`
#[derive(Debug, Clone, Deserialize, Overwrite)]
#[serde(default)]
struct FooterOptions {
    /// Every item you want to include in your footer
    items: Vec<String>,
    /// Overwrite footer with custom lmarkdown
    custom: Option<String>,
}
impl Default for FooterOptions {
    fn default() -> Self {
        Self {
            items: vec![
                r#"Generated by <a href="https://github.com/lyr-7D1h/lssg">LSSG</a>"#.to_string(),
            ],
            custom: None,
        }
    }
}

/// Options for the layout module, read from page attributes under `[layout]`
#[derive(Debug, Clone, Deserialize, Overwrite, Default)]
#[serde(default)]
struct LayoutOptions {
    /// Custom html fields in the footer
    footer: FooterOptions,
}

// TODO: use similar layout as https://quartz.jzhao.xyz/layout
#[derive(Default)]
struct Layout {
    left: Option<DomNode>,
    header: Option<DomNode>,
    footer: Option<DomNode>,
    right: Option<DomNode>,
}

#[derive(Default)]
pub struct LayoutModule {}

impl RendererModule for LayoutModule {
    fn id(&self) -> &'static str {
        "layout"
    }

    fn init(
        &mut self,
        ctx: crate::renderer::InitContext,
    ) -> Result<(), crate::lssg_error::LssgError> {
        let layout_css = ctx.site_tree.add(SiteNode::stylesheet(
            "layout.css",
            ctx.site_tree.root(),
            Stylesheet::from_readable(LAYOUT_STYLESHEET)?,
        ));
        for id in ctx.site_tree.pages().map(|(id, _)| id).collect::<Vec<_>>() {
            ctx.site_tree.add_link(id, layout_css, Relation::External);
        }
        Ok(())
    }

    fn after_render<'n>(
        &mut self,
        document: &mut Document,
        ctx: &RenderContext<'n>,
        tr: &mut TokenRenderer,
    ) {
        let options: LayoutOptions = self.propegated_options(ctx.site_id, ctx.site_tree);

        let mut layout = Layout::default();

        let footer = dom!(<footer style="grid-area:footer" class="layout__footer"></footer>);
        if let Some(custom_footer) = options.footer.custom.as_ref() {
            // render the custom footer through the same module chain as the page body
            match lmarkdown::parse_lmarkdown(custom_footer.as_bytes()) {
                Ok(tokens) => {
                    tr.render(document, ctx, footer.clone(), &tokens);
                    layout.footer = Some(footer);
                }
                Err(e) => warn!("Failed to parse custom footer: {e}"),
            }
        } else {
            let items = options.footer.items.clone();
            let mut items = items.into_iter().peekable();
            while let Some(item) = items.next() {
                if let Ok(item) = virtual_dom::parse_html_from_string(&item) {
                    footer.append_child(item);
                }
                if items.peek().is_some() {
                    footer.append_child(" | ");
                }
            }
            layout.footer = Some(footer);
        }

        for node in document.body.descendants() {
            let parent = {
                let DomNodeKind::Element { tag, attributes } = &*node.kind() else {
                    continue;
                };
                let section = match tag.as_str() {
                    "left" => layout
                        .left
                        .get_or_insert(DomNode::create_element("section")),
                    "header" => layout
                        .header
                        .get_or_insert(DomNode::create_element("section")),
                    "footer" => layout
                        .footer
                        .get_or_insert(DomNode::create_element("section")),
                    "right" => layout
                        .right
                        .get_or_insert(DomNode::create_element("section")),
                    _ => continue,
                };
                let mut style = format!("grid-area:{tag}");
                if let Some(s) = attributes.get("style") {
                    style += ";";
                    style.push_str(s);
                }
                section.set_attribute("style", &style);
                if let Some(id) = attributes.get("id") {
                    section.set_attribute("id", id);
                }
                section
            };
            node.detach();
            for child in node.children() {
                parent.append_child(child);
            }
        }

        let mut body = document.create_element("div");
        body.set_attribute("id", "layout__body");
        // body.set_attribute("style", &layout.grid_templates_areas());

        // remove all elements from body
        let content = document.create_element_with_attributes(
            "main",
            to_attributes([("style", "grid-area:content")]),
        );
        for child in document.body.children() {
            child.detach();
            content.append_child(child);
        }

        if let Some(section) = layout.left {
            body.append_child(section);
        }
        if let Some(section) = layout.header {
            body.append_child(section);
        }

        body.append_child(content);

        if let Some(section) = layout.right {
            body.append_child(section);
        }
        if let Some(section) = layout.footer {
            body.append_child(section);
        }

        document.body.prepend(body);
    }
}
