name: Lyrx Github Pages Deployment

on:
  push:
    branches: [ "master" ]
    paths:
        - examples/lyrx/**
  pull_request:
    branches: [ "master" ]
    paths:
        - examples/lyrx/**

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build static files
      working-directory: examples/lyrx/content
      run: cargo run -- .
      
    - name: Deploy to external repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.EXTERNAL_REPOSITORY_PERSONAL_ACCESS_TOKEN }}
      with:
        source-directory: examples/lyrx/build
        destination-github-username: lyr-7d1h
        destination-repository-name: lyrx
        user-email: lyr-7d1h@pm.me
        target-branch: master
