name: Lyrx Github Pages Deployment

on:
  push:
    branches: [ "master" ]
#     paths:
#         - examples/lyrx
  pull_request:
    branches: [ "master" ]
    paths:
        - examples/lyrx

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build static files
      working-directory: examples/lyrx/content
      run: cargo run -- .
      
    - name: Upload to static site repository
      working-directory: examples/lyrx/build
      run: |
        git init
        git remote add origin git@github.com:Lyr-7D1h/lyrx.git
        git add .
        git push
