name: Lyrx Github Pages Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build static files
      working-directory: examples/lyrx/content
      run: cargo run -- .
      
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: ./examples/lyrx/build
        
  deploy:
    needs: build
    permissions:
      pages: write      
      id-token: write
    environment:
      name: lyrx
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
