name: Lyrx Github Pages Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build static files
      working-directory: examples/lyrx
      run: cargo run
    - name: upload pages artifact
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: ./examples/lyrx/build
    - name: Deploy pages
      uses: actions/deploy-pages
