name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd examples/lyrx
    - name: Build
      run: cargo run
    - name: Upload to github pages
      uses: actions/upload-pages-artifact@v1.0.8
